version: '3'
services:
    db:
        container_name: sample_db2
        image: postgres:9.5
        volumes:
            - sample_db2:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=sample
            - POSTGRES_USER=sample
            - POSTGRES_DB=sample
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432

volumes:
    sample_db2: {}
